### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by IzaZed** [IzaZed/bricky-nodes#3]
- [ ] Add State Interface
- [ ] Data transfer on brick duplication
- [ ] rename package to bge_bricknodes
- [ ] Initial States
- [ ] State "mask" (collapse nodes by state)
- [ ] Object "mask" (collapse nodes by object)
- [ ] Data transfer on object change
